# Generated by Django 3.2 on 2021-04-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_blogs_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titile',
            new_name='title',
        ),
    ]
